#!/bin/sh

. libtest.sh

steps '
	:view-help
	:save-display help-default.screen

	:/View manipulation
	:save-display help-search.screen

	:3
	:enter
	:4
	:enter
	:save-display help-collapsed.screen
'

stdin <<EOF
test
EOF

test_tig

assert_equals 'help-default.screen' <<EOF
Quick reference for tig keybindings:
[-] Collapse all sections

[-] generic bindings
View switching
                           m view-main           Show main view
                           d view-diff           Show diff view
                           l view-log            Show log view
                           L view-reflog         Show reflog view
                           t view-tree           Show tree view
                           f view-blob           Show blob view
                           b view-blame          Show blame view
                           r view-refs           Show refs view
                        s, S view-status         Show status view
                           c view-stage          Show stage view
                           y view-stash          Show stash view
                           g view-grep           Show grep view
                           p view-pager          Show pager view
                           h view-help           Show help view
View manipulation
                     <Enter> enter               Enter and open selected line
                           < back                Go back to the previous view st
         <Down>, <Ctrl-N>, J next                Move to next
           <Up>, <Ctrl-P>, K previous            Move to previous
                         ',' parent              Move to parent
                       <Tab> view-next           Move focus to the next view
                     R, <F5> refresh             Reload and refresh view
                           O maximize            Maximize the current view
[help] - line 1 of 146                                                       19%
EOF

assert_equals 'help-search.screen' <<EOF
Quick reference for tig keybindings:
[-] Collapse all sections

[-] generic bindings
View switching
                           m view-main           Show main view
                           d view-diff           Show diff view
                           l view-log            Show log view
                           L view-reflog         Show reflog view
                           t view-tree           Show tree view
                           f view-blob           Show blob view
                           b view-blame          Show blame view
                           r view-refs           Show refs view
                        s, S view-status         Show status view
                           c view-stage          Show stage view
                           y view-stash          Show stash view
                           g view-grep           Show grep view
                           p view-pager          Show pager view
                           h view-help           Show help view
View manipulation
                     <Enter> enter               Enter and open selected line
                           < back                Go back to the previous view st
         <Down>, <Ctrl-N>, J next                Move to next
           <Up>, <Ctrl-P>, K previous            Move to previous
                         ',' parent              Move to parent
                       <Tab> view-next           Move focus to the next view
                     R, <F5> refresh             Reload and refresh view
                           O maximize            Maximize the current view
[help] - line 20 of 146                                                      19%
EOF

assert_equals 'help-collapsed.screen' <<EOF
Quick reference for tig keybindings:
[-] Collapse all sections

[+] generic bindings
[-] search bindings
View manipulation
                    <Ctrl-C> view-close          Close the current view
Searching
  <Down>, <Ctrl-N>, <Ctrl-J> find-next           Find next search match
    <Up>, <Ctrl-P>, <Ctrl-K> find-prev           Find previous search match
[-] main bindings
Option toggling:
  G :toggle commit-title-graph
  F :toggle commit-title-refs
Internal commands:
  H :goto HEAD
External commands:
  C ?git cherry-pick %(commit)
[-] diff bindings
Option toggling:
  [ :toggle diff-context -1
  ] :toggle diff-context +1
Internal commands:
  @ :/^@@
[-] reflog bindings
Option toggling:
  F :toggle commit-title-refs
External commands:
[help] - line 4 of 79                                                        35%
EOF
