#!/bin/sh

. libtest.sh
. libgit.sh

export LINES=16

tigrc <<EOF
set line-graphics = ascii

# Default view setting
set main-view = line-number:no,interval=5 id:no date:default author:full commit-title:yes,graph,refs,overflow=no

# Test change of view settings
set main-view-date = short
set main-view-line-number = yes
set main-view-author = abbreviated
set main-view-commit-title = yes,graph,refs=no

# Test change of of view column settings
set main-view-line-number-interval = 3
set main-view-id-display = yes
set main-view-id-width = 12
set main-view-commit-title-graph = no
EOF

steps '
	:save-display main-view.screen
'

git_clone 'repo-one'

test_tig

assert_equals 'main-view.screen' <<EOF
  1| 5cb3412a5e06 2010-04-07 MPower    Commit 10 E                              
   | 2843bfd58b98 2010-03-29 JTBrahe   Commit 10 D                              
  3| 8d53d6a41f85 2010-03-21 作者      Commit 10 C                            
   | 51b758035f2b 2010-03-12 RLévesque Commit 10 B                             
   | 19455fa3642a 2010-03-04 AUThor    Commit 10 A                              
  6| 276c3a4a8d90 2010-02-23 MPower    Commit 9 E                               
   | 5633519083f2 2010-02-15 JTBrahe   Commit 9 D                               
   | 711615619913 2010-02-06 作者      Commit 9 C                             
  9| 99278700109a 2010-01-29 RLévesque Commit 9 B                              
   | a3f25ca556c1 2010-01-20 AUThor    Commit 9 A                               
   | d9a8c8b1e52b 2010-01-12 MPower    Commit 8 E                               
 12| 545eb1fa92b9 2010-01-03 JTBrahe   Commit 8 D                               
   | b45b5704c34d 2009-12-26 作者      Commit 8 C                             
   | 957f2b368e6f 2009-12-17 RLévesque Commit 8 B                              
[main] 5cb3412a5e06e506840495b91acc885037a48b72 - commit 1 of 50             28%
EOF
