.\"     Title: tig
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 09/29/2007
.\"    Manual: Tig Manual
.\"    Source: Tig 0.9.1
.\"
.TH "TIG" "1" "09/29/2007" "Tig 0.9.1" "Tig Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
tig \- text\-mode interface for git
.SH "SYNOPSIS"
.sp
.nf
tig [options]
tig [options] [\-\-] [git options]
tig [options] log  [git options]
tig [options] diff [git options]
tig [options] show [git options]
tig [options] <    [git command output]

.fi
.SH "DESCRIPTION"
Browse changes in a git repository. Additionally, tig(1) can also act as a pager for output of various git commands.
.sp
When browsing repositories, tig(1) uses the underlying git commands to present the user with various views, such as summarized commit log and showing the commit with the log message, diffstat, and the diff.
.sp
Using tig(1) as a pager, it will display input from stdin and try to colorize it.
.sp
.SH "OPTIONS"
.PP
\-l
.RS 3n
Start up in log view using the internal log command.
.sp
.RE
.PP
\-d
.RS 3n
Start up in diff view using the internal diff command.
.sp
.RE
.PP
\-S
.RS 3n
Start up in status view.
.sp
.RE
.PP
\-n[INTERVAL], \-\-line\-number[=INTERVAL]
.RS 3n
Prefix line numbers in log and diff view. Optionally, with interval different than each line.
.sp
.RE
.PP
\-b[NSPACES], \-\-tab\-size[=NSPACES]
.RS 3n
Set the number of spaces tabs should be expanded to.
.sp
.RE
.PP
\-v, \-\-version
.RS 3n
Show version and exit.
.sp
.RE
.PP
\-h, \-\-help
.RS 3n
Show help message and exit.
.sp
.RE
.PP
\-\-
.RS 3n
End of tig(1) options. Useful when specifying command options for the main view. Example:
.sp
.sp
.nf
$ tig \-\- \-\-since=1.month

.fi
.RE
.PP
log
.RS 3n
Open log view using the given git log options.
.sp
.RE
.PP
diff
.RS 3n
Open diff view using the given git diff options.
.sp
.RE
.PP
show
.RS 3n
Open diff view using the given git show options.
.sp
.RE
.PP
[git options]
.RS 3n
tig(1) will stop the option parsing when the first command line parameter not starting with "\-" is encountered. All options including this one will be passed to git log when loading the main view. This makes it possible to say:
.sp
.sp
.nf
$ tig tag\-1.0..HEAD

.fi
.RE
.SH "ENVIRONMENT VARIABLES"
.PP
TIG_LS_REMOTE
.RS 3n
Set command for retrieving all repository references. The command should output data in the same format as git\-ls\-remote(1).
.sp
.RE
.PP
TIG_CHERRY_PICK
.RS 3n
Set command for cherry\-picking a commit. The command should expect a commit SHA as its final argument.
.sp
.RE
.PP
TIG_DIFF_CMD
.RS 3n
The command used for the diff view. By default, git show is used as a backend.
.sp
.RE
.PP
TIG_LOG_CMD
.RS 3n
The command used for the log view. If you prefer to have both author and committer shown in the log view be sure to pass \-\-pretty=fuller to git log.
.sp
.RE
.PP
TIG_MAIN_CMD
.RS 3n
The command used for the main view. Note, you must always specify the option: \-\-pretty=raw since the main view parser expects to read that format.
.sp
.RE
.SS "Tree commands"
.PP
TIG_TREE_CMD
.RS 3n
The command used for the tree view. By default, git\-ls\-tree(1) is used. The commands should expect first the commit ID and second a path.
.sp
.RE
.PP
TIG_BLOB_CMD
.RS 3n
The command used for the blob view. By default, git\-cat\-file(1) is used. The command gets the blob ID.
.sp
.RE
.SH "FILES"
.PP
\fI~/.tigrc\fR
.RS 3n
User configuration file. See \fBtigrc\fR(5) for examples.
.sp
.RE
.PP
\fI.git/config\fR
.RS 3n
Repository config file. Read on start\-up with the help of git\-repo\-config(1).
.sp
.RE
.SH "BUGS"
Known bugs and problems:
.sp
.TP 3n
\(bu
Proper locale support: in it's current state tig is pretty much UTF\-8 only.
.sp
.TP 3n
\(bu
Horizontal scrolling.
.sp
.SH "COPYRIGHT"
Copyright (c) 2006\-2007 Jonas Fonseca <fonseca@diku.dk>
.sp
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
.sp
.SH "SEE ALSO"
\fBtigrc\fR(5), git(7), cogito(7), as well as other git repository browsers: gitk(1), qgit(1), gitview(1).
.sp
Online resources:
.sp
.TP 3n
\(bu
Homepage: \fIhttp://jonas.nitro.dk/tig/\fR
.sp
.TP 3n
\(bu
Manual: \fIhttp://jonas.nitro.dk/tig/manual.html\fR
.sp
.TP 3n
\(bu
Tarballs: \fIhttp://jonas.nitro.dk/tig/releases/\fR
.sp
.TP 3n
\(bu
Git URL: git://repo.or.cz/tig.git (mirror) or \fIhttp://jonas.nitro.dk/tig/tig.git\fR (master)
.sp
.TP 3n
\(bu
Gitweb: \fIhttp://repo.or.cz/w/tig.git\fR
.sp
