.\"     Title: tig
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 03/17/2008
.\"    Manual: Tig Manual
.\"    Source: Tig 0.10-62-g1267e0a-dirty
.\"
.TH "TIG" "1" "03/17/2008" "Tig 0.10\-62\-g1267e0a\-dirty" "Tig Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
tig \- text\-mode interface for git
.SH "SYNOPSIS"
.sp
.RS 4
.nf
tig        [options] [revisions] [\-\-] [paths]
tig show   [options] [revisions] [\-\-] [paths]
tig status
tig <      [git command output]
.fi
.RE
.sp
.SH "DESCRIPTION"
Browse changes in a git repository. Additionally, tig(1) can also act as a pager for output of various git commands.
.sp
When browsing repositories, tig(1) uses the underlying git commands to present the user with various views, such as summarized commit log and showing the commit with the log message, diffstat, and the diff.
.sp
Using tig(1) as a pager, it will display input from stdin and try to colorize it.
.sp
.SH "OPTIONS"
Command line options recognized by tig include all valid git\-log(1) and git\-diff(1) options, as well as the following subcommands and tig specific options. The first command line parameter not starting with "\-" is interpreted as being either a revision specification or a path and will end the option parsing. All following options will be passed untouched to the underlying git command.
.sp
.PP
show
.RS 4
Open diff view using the given git show options.
.RE
.PP
status
.RS 4
Start up in status view.
.RE
.PP
\-v, \-\-version
.RS 4
Show version and exit.
.RE
.PP
\-h, \-\-help
.RS 4
Show help message and exit.
.RE
.PP
\-\-
.RS 4
End of tig options. This ends tig option parsing, and passes any following options untouched to the underlying git command. Kept for compatibility and will be deprecated in a future version.
.RE
.SH "EXAMPLES"
Display the current branch:
.sp
.sp
.RS 4
.nf
$ tig
.fi
.RE
.sp
Display one or more specific branches:
.sp
.sp
.RS 4
.nf
$ tig test master
.fi
.RE
.sp
Display all branches:
.sp
.sp
.RS 4
.nf
$ tig \-\-all
.fi
.RE
.sp
Display differences between two branches:
.sp
.sp
.RS 4
.nf
$ tig test..master
.fi
.RE
.sp
Display changes for a single file:
.sp
.sp
.RS 4
.nf
$ tig \-\- README
.fi
.RE
.sp
Display contents of the README file in a specific revision:
.sp
.sp
.RS 4
.nf
$ tig show tig\-0.8:README
.fi
.RE
.sp
Display revisions between two dates for a specific file:
.sp
.sp
.RS 4
.nf
$ tig \-\-after="2004\-01\-01" \-\-before="2006\-05\-16" \-\- README
.fi
.RE
.sp
.SH "ENVIRONMENT VARIABLES"
In addition to environment variables used by git (e.g. GIT_DIR), tig defines the following:
.sp
.PP
TIGRC_USER
.RS 4
Path of the user configuration file (defaults to
~/.tigrc).
.RE
.PP
TIGRC_SYSTEM
.RS 4
Path of the system wide configuration file (defaults to
++SYSCONFDIR++/tigrc).
.RE
.PP
TIG_LS_REMOTE
.RS 4
Set command for retrieving all repository references. The command should output data in the same format as git\-ls\-remote(1).
.RE
.PP
TIG_DIFF_CMD
.RS 4
The command used for the diff view. By default, git show is used as a backend.
.RE
.PP
TIG_LOG_CMD
.RS 4
The command used for the log view. If you prefer to have both author and committer shown in the log view be sure to pass
\-\-pretty=fuller
to git log.
.RE
.PP
TIG_MAIN_CMD
.RS 4
The command used for the main view. Note, you must always specify the option:
\-\-pretty=raw
since the main view parser expects to read that format.
.RE
.SS "Tree commands"
.PP
TIG_TREE_CMD
.RS 4
The command used for the tree view. By default, git\-ls\-tree(1) is used. The commands should expect first the commit ID and second a path.
.RE
.PP
TIG_BLOB_CMD
.RS 4
The command used for the blob view. By default, git\-cat\-file(1) is used. The command gets the blob ID.
.RE
.SH "FILES"
.PP
\fI~/.tigrc\fR
.RS 4
User configuration file. See
\fBtigrc\fR(5)
for examples.
.RE
.PP
\fI++SYSCONFDIR++/tigrc\fR
.RS 4
System wide configuration file.
.RE
.PP
\fI$GIT_DIR/config\fR
.RS 4
Repository config file. Read on start\-up with the help of git\-config(1).
.RE
.SH "BUGS"
Known bugs and problems:
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'Proper locale support: in it's current state tig is pretty much UTF\-8 only.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Horizontal scrolling.
.RE
.SH "COPYRIGHT"
Copyright (c) 2006\-2007 Jonas Fonseca <fonseca@diku.dk>
.sp
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
.sp
.SH "SEE ALSO"
\fBtigrc\fR(5), git(7), cogito(7), as well as other git repository browsers: gitk(1), qgit(1), gitview(1).
.sp
Online resources:
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'Homepage:
\fIhttp://jonas.nitro.dk/tig/\fR
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Manual:
\fIhttp://jonas.nitro.dk/tig/manual.html\fR
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Tarballs:
\fIhttp://jonas.nitro.dk/tig/releases/\fR
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Git URL: git://repo.or.cz/tig.git (mirror) or
\fIhttp://jonas.nitro.dk/tig/tig.git\fR
(master)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Gitweb:
\fIhttp://repo.or.cz/w/tig.git\fR
.RE
