#!/bin/sh

. libtest.sh
. libgit.sh
. "$source_dir/util.sh"

export LINES=16

steps '
	:set line-graphics = ascii
	:save-display merge-view.screen
'

in_work_dir create_dirty_workdir
in_work_dir setup-conflict.sh >> prepare.log 2>> prepare.log

test_tig --boundary --all ^master

assert_equals 'merge-view.screen' <<EOF
2009-03-28 13:22 +0000 Committer         * [conflict-branch] Change: d'
2009-03-20 01:00 +0000 Committer         * Change: d
2014-05-25 19:42 +0000 Not Committed Yet | * Unstaged changes
2009-03-11 12:38 +0000 Committer         | * [conflict-master] Change: c'
2009-03-03 00:15 +0000 Committer         | * Change: c
2009-02-22 11:53 +0000 Committer         o-' [master] Change: b
 
 
 
 
 
 
 
 
[main] d62d8545d99da3de587bf2ef43703dde0ce68084 - commit 1 of 5             100%
EOF
