#!/bin/sh

. libtest.sh
. libgit.sh

export LINES=10

tigrc <<EOF
set vertical-split = no
EOF

test_setup_work_dir()
{
	git_commit -m "🚑 Fix bug"
	git_commit -m "🐧 Fix Linux issue"
	git_commit -m "✨ Add new feature"
	git_commit -m "🎨 Reformat the code"
	git_commit -m "📚 Document new feature"
	git_commit -m "💄 Polish the UI"
	git_commit -m "🌏💧✋🕋🗡🚀🏜☀️🌡🌶💯🚱⏳🌅🌑😡💉😱😈💀💥🌛🌙🐭💥🚶🏻〰🐛️⌛️👳🙏💥😴🛌😳💥🐛💥👊⚔👑 "
}

git_init

test_case emoji-commit-titles-col-40 \
	--subshell='export COLUMNS=40' \
	<<EOF
2009-04-06 01:44 Committer o [master] 🌏💧
2009-03-28 13:22 Committer o 💄 Polish th
2009-03-20 01:00 Committer o 📚 Document
2009-03-11 12:38 Committer o 🎨 Reformat
2009-03-03 00:15 Committer o ✨ Add new f
2009-02-22 11:53 Committer o 🐧 Fix Linux
2009-02-13 23:31 Committer I 🚑 Fix bug

[main] 50a10e108b44c34548b9ba9e31841100%
EOF

run_test_cases
