#!/bin/sh
#
# Test display and options specific to the main view.

. libtest.sh
. libgit.sh

export LINES=16

tigrc <<EOF
set main-options = -n 10
EOF

steps '
	:save-display with-10-lines.screen
'

git_clone 'repo-one'

test_tig

assert_equals 'with-10-lines.screen' <<EOF
2010-04-07 05:37 Max Power             o [master] {origin/master} {origin/HEAD} 
2010-03-29 17:15 Jørgen Thygesen Brahe o Commit 10 D                           
2010-03-21 04:53 作者                  o Commit 10 C                          
2010-03-12 16:31 René Lévesque         o Commit 10 B                          
2010-03-04 04:09 A. U. Thor            o Commit 10 A                            
2010-02-23 15:46 Max Power             o Commit 9 E                             
2010-02-15 03:24 Jørgen Thygesen Brahe o Commit 9 D                            
2010-02-06 15:02 作者                  o Commit 9 C                           
2010-01-29 02:40 René Lévesque         o Commit 9 B                           
2010-01-20 14:18 A. U. Thor            o Commit 9 A                             
                                                                                
                                                                                
                                                                                
                                                                                
[main] 5cb3412a5e06e506840495b91acc885037a48b72 - commit 1 of 10            100%
EOF
