#!/bin/sh

. libtest.sh
. libgit.sh
. "$source_dir/util.sh"

export LINES=10

steps '
	:save-display main-with-conflict.screen
'

tigrc <<EOF
set vertical-split = no
set line-graphics = ascii
EOF

in_work_dir create_repo_from_tgz "$base_dir/files/scala-js-benchmarks.tgz"
in_work_dir setup-conflict.sh > repo.log 2>&1

test_tig --merge

assert_equals 'main-with-conflict.screen' <<EOF
2009-03-28 13:22 +0000 Committer         * [conflict-branch] Change: d'
2009-03-20 01:00 +0000 Committer         * Change: d
$YYY_MM_DD_HH_MM +0000 Not Committed Yet | * Unstaged changes
2009-03-11 12:38 +0000 Committer         | * [conflict-master] Change: c'
2009-03-03 00:15 +0000 Committer         | * Change: c
2009-02-22 11:53 +0000 Committer         o-' [master] Change: b
 
 
[main] 9d2a1bbf0046ec6b5e7a6faebb9ba9374bdbdee7 - commit 1 of 5             100%
EOF
