#!/bin/sh

. libtest.sh
. libgit.sh

export LINES=16

in_work_dir create_repo_from_tgz "$base_dir/files/scala-js-benchmarks.tgz"

steps '
	:save-display no-merges.screen
'


test_tig --no-merges

assert_equals 'no-merges.screen' <<EOF
2014-03-01 17:26 -0500 Jonas Fonseca      [master] WIP: Upgrade to 0.4-SNAPSHOT
2014-03-01 15:59 -0500 Jonas Fonseca      Add type parameter for js.Dynamic
2014-01-16 22:51 -0500 Jonas Fonseca      Move classes under org.scalajs.benchma
2014-01-16 17:43 -0500 Jonas Fonseca      Bump Scala.js version to 0.3-SNAPSHOT
2014-01-16 17:39 -0500 Jonas Fonseca      Integrate app code into the benchmark
2014-01-16 15:32 +0100 Philipp Haller     Fix link to Dart benchmark harness
2013-12-17 00:02 +0100 Jonas Fonseca      Update links to reflect project name c
2013-12-03 23:35 -0500 Jonas Fonseca      Use Scala.js 0.2-SNAPSHOT
2013-11-26 23:39 -0500 Jonas Fonseca      Extract the benchmark list variable na
2013-11-26 23:31 -0500 Jonas Fonseca      Solve the easiest sudoku grid
2013-11-26 23:22 -0500 Jonas Fonseca      Disable phantomjs by default
2013-11-26 22:55 -0500 Jonas Fonseca      Exclude Sudoku when running all benchm
2013-11-26 22:52 -0500 Jonas Fonseca      Fix reference setup to work for node
2013-11-26 22:03 -0500 Jonas Fonseca      Move benchmark registration to Scala
[main] ee912870202200a0b9cf4fd86ba57243212d341e - commit 1 of 45             31%
EOF
