#!/bin/sh

. libtest.sh
. libgit.sh

export WIDTH=40
export LINES=18

tigrc <<EOF
set vertical-split = auto
EOF

steps '
	:view-main
	:enter
	:save-display main-vsplit-default.screen

	:toggle split-view-width +25%
	:save-display main-vsplit-25-75.screen

	:set vertical-split = no
	:save-display main-hsplit-default.screen

	:toggle split-view-height -17%
	:save-display main-hsplit-50-50.screen
'

git_clone 'repo-one'

test_tig

assert_equals 'main-vsplit-default.screen' <<EOF
2010-04-07 05:37 Max Power             o|commit 5cb3412a5e06e506840495b91acc8850
2010-03-29 17:15 Jørgen Thygesen Brahe o|Refs: [master], {origin/master}, {orig
2010-03-21 04:53 作者                  o|Author:     Max Power <power123@examp
2010-03-12 16:31 René Lévesque         o|AuthorDate: Wed Apr 7 05:37:40 2010 +
2010-03-04 04:09 A. U. Thor            o|Commit:     Committer <c.ommitter@examp
2010-02-23 15:46 Max Power             o|CommitDate: Wed Apr 7 05:37:40 2010 +00
2010-02-15 03:24 Jørgen Thygesen Brahe o|                                      
2010-02-06 15:02 作者                  o|    Commit 10 E                      
2010-01-29 02:40 René Lévesque         o|                                     
2010-01-20 14:18 A. U. Thor            o|                                       
2010-01-12 01:56 Max Power             o|                                       
2010-01-03 13:33 Jørgen Thygesen Brahe o|                                      
2009-12-26 01:11 作者                  o|                                     
2009-12-17 12:49 René Lévesque         o|                                     
2009-12-09 00:27 A. U. Thor            o|                                       
2009-11-30 12:05 Max Power             o|                                       
[main] 5cb3412a5e06e506840495b91acc8832%|[diff] 5cb3412a5e06e506840495b91acc100%
EOF

assert_equals 'main-vsplit-25-75.screen' <<EOF
2010-04-07 05:37 Ma~ |commit 5cb3412a5e06e506840495b91acc885037a48b72           
2010-03-29 17:15 Jø~ |Refs: [master], {origin/master}, {origin/HEAD}           
2010-03-21 04:53 作~ |Author:     Max Power <power123@example.org>             
2010-03-12 16:31 Re~ |AuthorDate: Wed Apr 7 05:37:40 2010 +0000                 
2010-03-04 04:09 A.~ |Commit:     Committer <c.ommitter@example.net>            
2010-02-23 15:46 Ma~ |CommitDate: Wed Apr 7 05:37:40 2010 +0000                 
2010-02-15 03:24 Jø~ |                                                         
2010-02-06 15:02 作~ |    Commit 10 E                                          
2010-01-29 02:40 Re~ |                                                          
2010-01-20 14:18 A.~ |                                                          
2010-01-12 01:56 Ma~ |                                                          
2010-01-03 13:33 Jø~ |                                                         
2009-12-26 01:11 作~ |                                                         
2009-12-17 12:49 Re~ |                                                          
2009-12-09 00:27 A.~ |                                                          
2009-11-30 12:05 Ma~ |                                                          
[main] 5cb3412a5e032%|[diff] 5cb3412a5e06e506840495b91acc885037a48b72 - line100%
EOF

assert_equals 'main-hsplit-default.screen' <<EOF
2010-04-07 05:37 Max Power             o [master] {origin/master} {origin/HEAD} 
2010-03-29 17:15 Jørgen Thygesen Brahe o Commit 10 D                           
2010-03-21 04:53 作者                  o Commit 10 C                          
2010-03-12 16:31 René Lévesque         o Commit 10 B                          
2010-03-04 04:09 A. U. Thor            o Commit 10 A                            
[main] 5cb3412a5e06e506840495b91acc885037a48b72 - commit 1 of 50             10%
commit 5cb3412a5e06e506840495b91acc885037a48b72                                 
Refs: [master], {origin/master}, {origin/HEAD}                                  
Author:     Max Power <power123@example.org>                                    
AuthorDate: Wed Apr 7 05:37:40 2010 +0000                                       
Commit:     Committer <c.ommitter@example.net>                                  
CommitDate: Wed Apr 7 05:37:40 2010 +0000                                       
                                                                                
    Commit 10 E                                                                 
                                                                                
                                                                                
[diff] 5cb3412a5e06e506840495b91acc885037a48b72 - line 1 of 8               100%
EOF

assert_equals 'main-hsplit-50-50.screen' <<EOF
2010-04-07 05:37 Max Power             o [master] {origin/master} {origin/HEAD} 
2010-03-29 17:15 Jørgen Thygesen Brahe o Commit 10 D                           
2010-03-21 04:53 作者                  o Commit 10 C                          
2010-03-12 16:31 René Lévesque         o Commit 10 B                          
2010-03-04 04:09 A. U. Thor            o Commit 10 A                            
2010-02-23 15:46 Max Power             o Commit 9 E                             
2010-02-15 03:24 Jørgen Thygesen Brahe o Commit 9 D                            
2010-02-06 15:02 作者                  o Commit 9 C                           
[main] 5cb3412a5e06e506840495b91acc885037a48b72 - commit 1 of 50             16%
commit 5cb3412a5e06e506840495b91acc885037a48b72                                 
Refs: [master], {origin/master}, {origin/HEAD}                                  
Author:     Max Power <power123@example.org>                                    
AuthorDate: Wed Apr 7 05:37:40 2010 +0000                                       
Commit:     Committer <c.ommitter@example.net>                                  
CommitDate: Wed Apr 7 05:37:40 2010 +0000                                       
                                                                                
[diff] 5cb3412a5e06e506840495b91acc885037a48b72 - line 1 of 8                87%
EOF
