#!/bin/sh

. libtest.sh
. libgit.sh

export LINES=41
export COLUMNS=130

tigrc <<EOF
set vertical-split = no
set recurse-tree = yes
EOF

steps '
	:view-tree
	:save-display tree-recurse.screen
'

in_work_dir create_repo_from_tgz "$base_dir/files/scala-js-benchmarks.tgz"

test_tig

assert_equals 'tree-recurse.screen' <<EOF
Directory path /
-rw-r--r-- Jonas Fonseca     53 2013-10-14 16:19 -0400 .gitignore
-rw-r--r-- Jonas Fonseca   1499 2013-10-26 12:54 -0400 LICENSE
-rw-r--r-- Philipp Haller  2609 2014-01-16 15:32 +0100 README.md
-rwxr-xr-x Jonas Fonseca   2875 2014-03-01 17:26 -0500 common/benchmark-runner.sh
-rw-r--r-- Jonas Fonseca      0 2013-10-14 14:56 -0400 common/build.sbt
-rw-r--r-- Jonas Fonseca    702 2013-10-26 12:54 -0400 common/d8-stubs.js
-rw-r--r-- Jonas Fonseca    836 2013-10-27 23:05 -0400 common/reference/bench.js
-rw-r--r-- Jonas Fonseca  25799 2014-01-16 17:39 -0500 common/reference/deltablue.js
-rw-r--r-- Jonas Fonseca  15926 2014-01-16 17:39 -0500 common/reference/richards.js
-rw-r--r-- Jonas Fonseca  28143 2014-01-16 17:39 -0500 common/reference/tracer.js
-rw-r--r-- Jonas Fonseca   3121 2014-03-01 17:26 -0500 common/src/main/scala/org/scalajs/benchmark/Benchmark.scala
-rw-r--r-- Jonas Fonseca   1380 2014-03-01 17:26 -0500 common/src/main/scala/org/scalajs/benchmark/BenchmarkApp.scala
-rw-r--r-- Jonas Fonseca   1500 2014-01-16 22:51 -0500 common/src/main/scala/org/scalajs/benchmark/dom/DOMTypes.scala
-rw-r--r-- Jonas Fonseca    811 2014-03-01 17:26 -0500 common/start-benchmark.js
-rwxr-xr-x Jonas Fonseca    355 2013-10-26 12:54 -0400 deltablue/run.sh
-rw-r--r-- Jonas Fonseca  22563 2014-03-01 17:26 -0500 deltablue/src/main/scala/org/scalajs/benchmark/deltablue/DeltaBlue.scala
-rw-r--r-- Jonas Fonseca   1686 2014-03-01 17:26 -0500 project/Build.scala
-rw-r--r-- Jonas Fonseca     19 2013-10-14 14:56 -0400 project/build.properties
-rw-r--r-- Jonas Fonseca    216 2014-03-01 17:26 -0500 project/build.sbt
-rw-r--r-- Jonas Fonseca      0 2013-10-17 20:34 -0400 richards/build.sbt
-rwxr-xr-x Jonas Fonseca    355 2013-10-26 12:54 -0400 richards/run.sh
-rw-r--r-- Jonas Fonseca  13931 2014-03-01 17:26 -0500 richards/src/main/scala/org/scalajs/benchmark/richards/Richards.scala
-rwxr-xr-x Jonas Fonseca    493 2014-03-01 17:26 -0500 run.sh
-rwxr-xr-x Jonas Fonseca    355 2013-11-11 01:11 -0500 sudoku/run.sh
-rw-r--r-- Jonas Fonseca   6958 2014-03-01 17:26 -0500 sudoku/src/main/scala/org/scalajs/benchmark/sudoku/Sudoku.scala
-rw-r--r-- Jonas Fonseca      0 2013-10-14 14:56 -0400 tracer/build.sbt
-rw-r--r-- Jonas Fonseca   1290 2014-03-01 17:26 -0500 tracer/index-dev.html
-rw-r--r-- Jonas Fonseca   1116 2014-03-01 17:26 -0500 tracer/index.html
-rwxr-xr-x Jonas Fonseca    355 2013-10-26 12:54 -0400 tracer/run.sh
-rw-r--r-- Jonas Fonseca   1427 2014-01-16 22:51 -0500 tracer/src/main/scala/org/scalajs/benchmark/tracer/App.scala
-rw-r--r-- Jonas Fonseca   1964 2014-01-16 22:51 -0500 tracer/src/main/scala/org/scalajs/benchmark/tracer/Color.scala
-rw-r--r-- Jonas Fonseca   5726 2014-01-16 22:51 -0500 tracer/src/main/scala/org/scalajs/benchmark/tracer/Engine.scala
-rw-r--r-- Jonas Fonseca   2000 2014-01-16 22:51 -0500 tracer/src/main/scala/org/scalajs/benchmark/tracer/Material.scala
-rw-r--r-- Jonas Fonseca   2142 2014-01-16 22:51 -0500 tracer/src/main/scala/org/scalajs/benchmark/tracer/RenderScene.scala
-rw-r--r-- Jonas Fonseca   1898 2014-01-16 22:51 -0500 tracer/src/main/scala/org/scalajs/benchmark/tracer/Scene.scala
-rw-r--r-- Jonas Fonseca   3060 2014-01-16 22:51 -0500 tracer/src/main/scala/org/scalajs/benchmark/tracer/Shapes.scala
-rw-r--r-- Jonas Fonseca   1329 2014-03-01 17:26 -0500 tracer/src/main/scala/org/scalajs/benchmark/tracer/Tracer.scala
-rw-r--r-- Jonas Fonseca   1751 2014-01-16 22:51 -0500 tracer/src/main/scala/org/scalajs/benchmark/tracer/Vector.scala
[tree] be06d7d413c0b3f2d2f6f18061c8bfb65c510b64 - file 1 of 38                                                                100%
EOF
