#!/bin/sh

. libtest.sh
. libgit.sh

export LINES=5

in_work_dir create_repo_from_tgz "$base_dir/files/scala-js-benchmarks.tgz"

steps '
	:set line-graphics = ascii
	# comment
	:save-display main.screen
'

test_tig

assert_equals main.screen <<EOF
2014-03-01 17:26 Jonas Fonseca      * [master] WIP: Upgrade to 0.4-SNAPSHOT and
2014-03-01 15:59 Jonas Fonseca      * Add type parameter for js.Dynamic
2014-01-16 22:51 Jonas Fonseca      * Move classes under org.scalajs.benchmark p
[main] ee912870202200a0b9cf4fd86ba57243212d341e - commit 1 of 48              6%
EOF
