#!/bin/sh

. libtest.sh
. libgit.sh

LINES=5

in_work_dir create_repo_from_tgz "$base_dir/files/scala-js-benchmarks.tgz"

tigrc <<EOF
set line-graphics = ascii
EOF

steps "
	:set-register a value
	:exec !assert-var %(register:a) == value

	:set-register a
	:exec !assert-var %(register:a) == value

	:set-register a overwrote_value
	:exec !assert-var %(register:a) == overwrote_value

	:exec =(a)echo shell_value
	:exec !assert-var %(register:a) == shell_value

	:exec !=(a)echo bang_shell_value
	:exec !assert-var %(register:a) == bang_shell_value

	:set-register b %(commit)
	:exec !assert-var %(register:b) == ee912870202200a0b9cf4fd86ba57243212d341e

	:exec !assert-var X%(register:c) == X

	:set-register \\c value
	:exec !assert-var X%(register:c) == X

	:set-register cc value
	:exec !assert-var X%(register:c) == X

	:set-register cvalue
	:exec !assert-var X%(register:c) == X

	:exec =(\\c)echo value
	:exec !assert-var X%(register:c) == X

	:set-register \\( value
	:exec !assert-var %(register:\\() == value

	:set-register ( unescaped_value
	:exec !assert-var %(register:() == unescaped_value
	:exec !assert-var %(register:\\() == unescaped_value

	:exec =(\\()echo shell_value
	:exec !assert-var %(register:\\() == shell_value

	:exec =(()echo unescaped_shell_value
	:exec !assert-var %(register:\\() == unescaped_shell_value

	:set-register \\\" value
	:exec !assert-var '%(register:\\\")' == value

	:set-register \" unescaped_value
	:exec !assert-var '%(register:\")' == unescaped_value
	:exec !assert-var '%(register:\\\")' == unescaped_value

	:exec =(\\\")echo shell_value
	:exec !assert-var '%(register:\\\")' == shell_value

	:exec =(\")echo unescaped_shell_value
	:exec !assert-var '%(register:\\\")' == unescaped_shell_value

	:set-register \\' value
	:exec !assert-var \"%(register:\\')\" == value

	:set-register ' unescaped_value
	:exec !assert-var \"%(register:')\" == unescaped_value
	:exec !assert-var \"%(register:\\')\" == unescaped_value

	:exec =(\\')echo shell_value
	:exec !assert-var \"%(register:\\')\" == shell_value

	:exec =(')echo unescaped_shell_value
	:exec !assert-var \"%(register:\\')\" == unescaped_shell_value

	:set-register b   strip leading space
	:exec !assert-var %(register:b) == 'strip leading space'

	:set-register '   strip leading space handle irregular unbalanced
	:exec !assert-var \"%(register:')\" == 'strip leading space handle irregular unbalanced'

	:set-register '   strip leading space coerce irregular balanced'
	:exec !assert-var \"%(register:')\" == \"strip leading space coerce irregular balanced'\"

	:save-display main.screen
"
test_tig

assert_equals stderr <<EOF
EOF

assert_equals main.screen <<EOF
2014-03-01 17:26 -0500 Jonas Fonseca      * [master] WIP: Upgrade to 0.4-SNAPSHO
2014-03-01 15:59 -0500 Jonas Fonseca      * Add type parameter for js.Dynamic
2014-01-16 22:51 -0500 Jonas Fonseca      * Move classes under org.scalajs.bench
[main] ee912870202200a0b9cf4fd86ba57243212d341e - commit 1 of 48              6%
EOF

assert_vars 29
