#!/bin/sh

. libtest.sh
. libgit.sh

steps '
	:set line-graphics = ascii
	:set diff-view-line-number = yes

	:210
	:scroll-line-down
	:save-display diff-default.screen

	:edit

	:224
	:edit
'

in_work_dir create_repo_from_tgz "$base_dir/files/scala-js-benchmarks.tgz"

test_tig show ee912870202200a0b9cf4fd86ba57243212d341e

assert_equals 'diff-default.screen' <<EOF
   | -  )                                                                       
   | -                                                                          
   |    lazy val parent: Project = Project(                                     
200|        id = "parent",                                                      
   |        base = file("."),                                                   
   | @@ -53,10 +48,10 @@ object ScalaJSBenchmarks extends Build {               
   |    )                                                                       
   |                                                                            
205|    lazy val common = project("Common", defaultSettings)                    
   | -  lazy val deltablue = project("DeltaBlue", benchmarkSettings).dependsOn(c
   | -  lazy val richards = project("Richards", benchmarkSettings).dependsOn(com
   | -  lazy val sudoku = project("Sudoku", benchmarkSettings).dependsOn(common)
   | -  lazy val tracer = project("Tracer", benchmarkSettings).dependsOn(common)
210| +  lazy val deltablue = project("DeltaBlue", defaultSettings).dependsOn(com
   | +  lazy val richards = project("Richards", defaultSettings).dependsOn(commo
   | +  lazy val sudoku = project("Sudoku", defaultSettings).dependsOn(common)  
   | +  lazy val tracer = project("Tracer", defaultSettings).dependsOn(common)  
   |                                                                            
215|    def project(id: String, settings: Seq[sbt.Def.Setting[_]]) = Project(   
   |        id = id.toLowerCase,                                                
   | diff --git a/project/build.sbt b/project/build.sbt                         
   | index 87c2e66..122abd0 100644                                              
   | --- a/project/build.sbt                                                    
220| +++ b/project/build.sbt                                                    
   | @@ -1 +1,4 @@                                                              
   | -addSbtPlugin("org.scala-lang.modules.scalajs" % "scalajs-sbt-plugin" % "0.
   | +resolvers += Resolver.url("scala-js-snapshots",                           
   | +    url("http://repo.scala-js.org/repo/snapshots/"))(Resolver.ivyStylePatt
[diff] Changes to 'project/Build.scala' - line 210 of 367                    61%
EOF

assert_equals 'editor.log' <<EOF
+51 project/Build.scala
  lazy val deltablue = project("DeltaBlue", defaultSettings).dependsOn(common)
+2 project/build.sbt
    url("http://repo.scala-js.org/repo/snapshots/"))(Resolver.ivyStylePatterns)
EOF
