#!/bin/sh

. libtest.sh
. libgit.sh

in_work_dir create_repo_from_tgz "$base_dir/files/scala-js-benchmarks.tgz"

steps '
	:save-display position.screen
'

#test_tig show master~18 +42
test_tig show d92a308941e6ccb79cb02f96417cab7b67b998c2 +42

assert_equals 'position.screen' <<EOF
       )                                                                        
@@ -47,12 +48,14 @@ object ScalaJSBuild extends Build {                         
       common,                                                                  
       deltablue,                                                               
       richards,                                                                
+      sudoku,                                                                  
       tracer                                                                   
   )                                                                            
                                                                                
   lazy val common = project("Common", defaultSettings)                         
   lazy val deltablue = project("DeltaBlue", benchmarkSettings).dependsOn(common
   lazy val richards = project("Richards", benchmarkSettings).dependsOn(common) 
+  lazy val sudoku = project("Sudoku", benchmarkSettings).dependsOn(common)     
   lazy val tracer = project("Tracer", benchmarkSettings).dependsOn(common)     
                                                                                
   def project(id: String, settings: Seq[sbt.Def.Setting[_]]) = Project(        
diff --git a/sudoku/Sudoku.scala b/sudoku/Sudoku.scala                          
new file mode 100644                                                            
index 0000000..3109fb7                                                          
--- /dev/null                                                                   
+++ b/sudoku/Sudoku.scala                                                       
@@ -0,0 +1,182 @@                                                               
+/*                     __                                               *\     
+**     ________ ___   / /  ___      __ ____  Scala.js Benchmarks        **     
+**    / __/ __// _ | / /  / _ | __ / // __/  (c) 2013, Jonas Fonseca    **     
+**  __\ \/ /__/ __ |/ /__/ __ |/_// /_\ \                               **     
+** /____/\___/_/ |_/____/_/ | |__/ /____/                               **     
+**                          |/____/                                     **     
[diff] Changes to 'project/Build.scala' - line 42 of 280                     19%
EOF
