tig(1)
======

NAME
----
tig - text-mode interface for git

SYNOPSIS
--------
[verse]
_______________________________________________________________________
tig        [options] [revisions] [--] [paths]
tig log    [options] [revisions] [--] [paths]
tig show   [options] [revisions] [--] [paths]
tig blame  [options] [rev] [--] path
tig stash
tig status
tig <      [git command output]
_______________________________________________________________________

DESCRIPTION
-----------
Browse changes in a git repository. Additionally, tig(1) can also act
as a pager for output of various git commands.

When browsing repositories, tig(1) uses the underlying git commands
to present the user with various views, such as summarized commit log
and showing the commit with the log message, diffstat, and the diff.

Using tig(1) as a pager, it will display input from stdin and try
to colorize it.

OPTIONS
-------

Command line options recognized by tig include all valid git-log(1) and
git-diff(1) options, as well as the following subcommands and tig specific
options. The first command line parameter not starting with "-" is interpreted
as being either a revision specification or a path and will end the option
parsing. All following options will be passed untouched to the underlying git
command.

show::
	Open diff view using the given git-show(1) options.

blame::
	Show given file annotated by commits.
	Takes zero or more git-blame(1) options.
	Optionally limited from given revision.

status::
	Start up in status view.

log::
	Start up in log view, displaying git-log(1) output.

+<number>::
    Show the first view with line <number> visible and selected.

-v, --version::
	Show version and exit.

-h, --help::
	Show help message and exit.

EXAMPLES
--------

Display the current branch:
-----------------------------------------------------------------------------
$ tig
-----------------------------------------------------------------------------

Display one or more specific branches:
-----------------------------------------------------------------------------
$ tig test master
-----------------------------------------------------------------------------

Display all branches:
-----------------------------------------------------------------------------
$ tig --all
-----------------------------------------------------------------------------

Display differences between two branches:
-----------------------------------------------------------------------------
$ tig test..master
-----------------------------------------------------------------------------

Display changes for sub-module versions:
-----------------------------------------------------------------------------
$ tig --submodule
-----------------------------------------------------------------------------

Display changes for a single file:
-----------------------------------------------------------------------------
$ tig -- README
-----------------------------------------------------------------------------

Display contents of the README file in a specific revision:
-----------------------------------------------------------------------------
$ tig show tig-0.8:README
-----------------------------------------------------------------------------

Display revisions between two dates for a specific file:
-----------------------------------------------------------------------------
$ tig --after="2004-01-01" --before="2006-05-16" -- README
-----------------------------------------------------------------------------

Blame file with copy detection enabled:
-----------------------------------------------------------------------------
$ tig blame -C README
-----------------------------------------------------------------------------

Display the list of stashes:
-----------------------------------------------------------------------------
$ tig stash
-----------------------------------------------------------------------------

ENVIRONMENT VARIABLES
---------------------

In addition to environment variables used by git (e.g. GIT_DIR), tig defines
the ones below. The command related environment variables have access to the
internal state of tig via replacement variables, such as `%(commit)` and
`%(blob)`.
ifdef::version[]
See manpage:tigrc[5] for a full list.
endif::version[]
ifndef::version[]
See link:tigrc.5.asciidoc[tigrc(5)] for a full list.
endif::version[]

TIGRC_USER::
	Path of the user configuration file (defaults to `~/.tigrc`).

TIGRC_SYSTEM::
	Path of the system wide configuration file (defaults to
	`{sysconfdir}/tigrc`).

TIG_LS_REMOTE::
	Set command for retrieving all repository references. The command
	should output data in the same format as git-ls-remote(1).

TIG_DIFF_OPTS::
	The diff options to use in the diff view. The diff view uses
	git-show(1) for formatting and always passes --patch-with-stat.  You
	may also set the diff-options setting in your manpage:tigrc[5].

TIG_TRACE::
	Path for trace file where information about git commands are logged.

FILES
-----
'~/.tigrc'::
	User configuration file. See manpage:tigrc[5] for examples.

'{sysconfdir}/tigrc'::
	System wide configuration file.

'$GIT_DIR/config'::
'~/.gitconfig::
'{sysconfdir}/etc/gitconfig::
	Git configuration files. Read on start-up with the help of
	git-config(1).

ifndef::version[]
include::../BUGS[]
endif::version[]

COPYRIGHT
---------
Copyright (c) 2006-2012 Jonas Fonseca <fonseca@diku.dk>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

SEE ALSO
--------
ifndef::version[]
link:tigrc.5.asciidoc[tigrc(5)],
link:manual.asciidoc[the tig manual],
endif::version[]
ifdef::version[]
ifdef::backend-docbook[]
manpage:tigrc[5],
manpage:tigmanual[7],
endif::backend-docbook[]
ifdef::backend-xhtml11[]
link:tigrc.5.html[tigrc(5)],
link:manual.html[the tig manual],
endif::backend-xhtml11[]
endif::version[]
git(7)
