#!/bin/sh

. libtest.sh
. libgit.sh

LINES=10

in_work_dir create_repo_from_tgz "$base_dir/files/scala-js-benchmarks.tgz"

test_case exec-without-arg-doesnt-crash \
	--args='status' \
	--script='
	:exec
	' <<EOF
On branch master
Changes to be committed:
  (no files)
Changes not staged for commit:
  (no files)
Untracked files:
  (no files)

[status] Nothing to update                                                  100%
EOF

test_case exec-only-flags-doesnt-crash \
	--args='status' \
	--script='
	:exec !
	' <<EOF
On branch master
Changes to be committed:
  (no files)
Changes not staged for commit:
  (no files)
Untracked files:
  (no files)

[status] Nothing to update                                                  100%
EOF

run_test_cases
