#!/bin/sh

. libtest.sh
. libgit.sh

export LINES=3
export COLUMNS=80

test_require readline

in_work_dir create_repo_from_tgz "$base_dir/files/scala-js-benchmarks.tgz"

tigrc <<EOF
set history-size = 3
EOF

keystrokes                 ':none'
keystrokes -append -keysym 'Enter'
keystrokes -append         ':quit'
keystrokes -append -keysym 'Enter'

test_tig

assert_equals stderr <<EOF
EOF

assert_equals "$HOME/.tig_history" <<EOF
none
quit
EOF
