#!/bin/sh

. libtest.sh
. libgit.sh

export LINES=3
export COLUMNS=80

test_require readline

in_work_dir create_repo_from_tgz "$base_dir/files/scala-js-benchmarks.tgz"

test_case one \
	--before='rm -f -- "$HOME/.tig_history"' \
	--tigrc='set history-size = 10' \
	--keystrokes=':echo keys_one\r:quit\r' \
	--assert-equals=".tig_history"='echo keys_one
quit
' \
<<EOF
2014-03-01 17:26 -0500 Jonas Fonseca      o [master] WIP: Upgrade to 0.4-SNAPSHO
[main] ee912870202200a0b9cf4fd86ba57243212d341e - commit 1 of 48              2%
EOF

test_case two \
	--before='rm -f -- "$HOME/.tig_history"' \
	--tigrc='set history-size = 10' \
	--keystrokes=':echo keys_two\r:quit\r' \
	--assert-equals=".tig_history"="echo keys_two
quit
" \
	--script=':echo first_line
:echo second_line' \
<<EOF
2014-03-01 17:26 -0500 Jonas Fonseca      o [master] WIP: Upgrade to 0.4-SNAPSHO
[main] ee912870202200a0b9cf4fd86ba57243212d341e - commit 1 of 48              2%
EOF

test_case three \
	--before='rm -f -- "$HOME/.tig_history"' \
	--tigrc='set history-size = 10' \
	--keystrokes=':echo keys_four\r:quit\r' \
	--assert-equals=".tig_history"='echo keys_four
quit
' \
<<EOF
2014-03-01 17:26 -0500 Jonas Fonseca      o [master] WIP: Upgrade to 0.4-SNAPSHO
[main] ee912870202200a0b9cf4fd86ba57243212d341e - commit 1 of 48              2%
EOF

run_test_cases
