#!/bin/sh
#
# Graph test: merge from left

. libtest.sh

test_graph <<EOF
commit A B C
    Commit A - Merge C into B
commit C B D
    Commit C - Merge D into B
commit B E
    Commit B after E
commit E D
    Commit E after D
commit D
    Commit D
EOF

assert_equals stdout <<EOF
●─╮ Commit A - Merge C into B
│ ●─╮ Commit C - Merge D into B
●─╯ │ Commit B after E
● ╭─╯ Commit E after D
◎─╯ Commit D
EOF
