#!/bin/sh
#
# Graph test: octo merge

. libtest.sh

test_graph <<EOF
commit A B C D
    Commit A - Merges B, C, and D
commit C E
    Commit C after E
commit E D B
    Commit E - Merges D and B
commit B D
    Commit B after D
commit D
    Commit D
EOF

assert_equals stdout <<EOF
●─┬─╮ Commit A - Merges B, C, and D
│ ● │ Commit C after E
│ ●─│─╮ Commit E - Merges D and B
●─│─│─╯ Commit B after D
◎─┴─╯ Commit D
EOF
