#!/bin/sh
#
# Graph test: missing bar

. libtest.sh

test_graph <<EOF
commit A B C
    Commit A - Merge B and C
commit B D E
    Commit B - Merge D and E
commit C F
    Commit C after F
commit F G D
    Commit F - Merge G and D
commit D G
    Commit D after G
commit G E
    Commit G after E
commit E
    Commit E
EOF

assert_equals stdout <<EOF
●─╮ Commit A - Merge B and C
●─│─╮ Commit B - Merge D and E
│ ● │ Commit C after F
│ ●─│─╮ Commit F - Merge G and D
●─│─│─╯ Commit D after G
●─╯ │ Commit G after E
◎───╯ Commit E
EOF
