#!/bin/sh
#
# Graph test: new branch in middle

. libtest.sh

test_graph <<EOF
commit A B C E
    Commit A - merge B, C, and E
commit B F
    Commit B - after F
commit C F
    Commit C - after F
commit E Z
    Commit E - after Z
commit F G I
    Commit F - merge G and I
commit G H I
    Commit F - merge H and I
commit H I
    Commit H - after I
commit I Z
    Commit I - after Z
commit Z
    Commit Z
EOF

assert_equals stdout <<EOF
●─┬─╮ Commit A - merge B, C, and E
● │ │ Commit B - after F
│ ● │ Commit C - after F
│ │ ● Commit E - after Z
●─╯ │ Commit F - merge G and I
●─│─│─╮ Commit F - merge H and I
● │ │ │ Commit H - after I
●─┴─│─╯ Commit I - after Z
◎───╯ Commit Z
EOF
