#!/bin/sh
#
# Graph test: tig

. libtest.sh

test_graph <<EOF
commit i h
    Do not include merges in the announcement's change log
commit h g d
    Merge pull request #81 from esc/fix/reading_git_colors_256
commit g f e
    Merge pull request #80 from esc/fix/option_name_mismatch
commit f c
    Reenable copy/rename detection in the status view
commit e c
    fix: the manpage says 'read-git-colors'
commit d c
    fix: reading git colors in rang 0 255
commit c b
    Remove enforced diff move/copy detection
commit b a
    Optionally show commit IDs for branches and tree entries
EOF

assert_equals stdout <<EOF
∙ Do not include merges in the announcement's change log
●─╮ Merge pull request #81 from esc/fix/reading_git_colors_256
●─│─╮ Merge pull request #80 from esc/fix/option_name_mismatch
∙ │ │ Reenable copy/rename detection in the status view
│ │ ∙ fix: the manpage says 'read-git-colors'
│ ∙ │ fix: reading git colors in rang 0 255
∙─┴─╯ Remove enforced diff move/copy detection
∙ Optionally show commit IDs for branches and tree entries
EOF
