#!/bin/sh

. libtest.sh
. libgit.sh

test_setup_work_dir()
{
	create_repo_from_tgz "$base_dir/files/scala-js-benchmarks.tgz"
	for i in $(seq 1 40); do
		git branch "ref-$i" "master~$i"
	done
}

steps '
	:save-display position.screen
'

test_tig refs +42

assert_equals 'position.screen' <<EOF
2013-10-27 18:12 -0400 Jonas Fonseca ref-26         Add check sum calculation fo
2013-10-26 12:54 -0400 Jonas Fonseca ref-27         Add Scala.js LICENSE file an
2013-10-25 22:08 -0400 Jonas Fonseca ref-28         Add script to build and run
2013-10-25 20:29 -0400 Jonas Fonseca ref-29         Support node as a JavaScript
2013-10-25 00:34 -0400 Jonas Fonseca ref-30         Run benchmarks for a fixed n
2013-10-24 23:50 -0400 Jonas Fonseca ref-31         Rework the benchmark runner
2013-10-20 00:23 -0700 Jonas Fonseca ref-32         Add DeltaBlue benchmark
2013-10-18 17:18 -0400 Jonas Fonseca ref-34         Use case class apply constru
2013-10-18 17:18 -0400 Jonas Fonseca ref-33         Tidyup indentation
2013-10-18 07:00 -0700 Jonas Fonseca ref-35         Merge pull request #1 from s
2013-10-17 20:34 -0400 Jonas Fonseca ref-36         Add Richards benchmark
2013-10-17 20:29 -0400 Jonas Fonseca ref-37         Simplify render scene loop b
2013-10-17 20:27 -0400 Jonas Fonseca ref-38         Make the run shell script in
2013-10-17 20:25 -0400 Jonas Fonseca ref-39         Simplify creation of new ben
2013-10-14 16:37 -0400 Jonas Fonseca ref-40         Add link to the github pages
 
 
 
 
 
 
 
 
 
 
 
 
 
[refs] 47b3bf58e19dceae53294e8d110828bd537f3752 - reference 41 of 41        100%
EOF
