#!/bin/sh

. libtest.sh
. libgit.sh

export COLUMNS=40

steps '
	:view-tree
	:/README.md
	:view-blob
	:save-display wrapped.screen
'

tigrc <<EOF
set line-graphics = utf-8
set wrap-lines = true
EOF

in_work_dir create_repo_from_tgz "$base_dir/files/scala-js-benchmarks.tgz"

test_tig

assert_equals 'wrapped.screen' <<EOF
# Scala.js Benchmarks                   
                                        
This is a port of the Dart              
[benchmark harness](https://github.com/d
+art-lang/benchmark_harness) to         
[Scala.js](https://github.com/scala-js/s
+cala-js).                              
                                        
You can see the benchmarks in action    
[here](http://jonas.github.io/scala-js-b
+enchmarks/).                           
                                        
All derivative work is the copyright of 
+their respective authors and           
distributed under their original license
+. All original work unless otherwise   
stated is distributed under the [same li
+cense as                               
Scala.js](https://github.com/jonas/scala
+-js-benchmarks/LICENSE).               
                                        
## Get started                          
                                        
To run the benchmarks, first install the
+ Scala.js compiler by following the    
instructions in the [Scala.js README](ht
+tps://github.com/lampepfl/scala-js).   
                                        
[blob] README.md - line 1 of 62      28%
EOF
