name: macOS

on: [push, pull_request]

jobs:
  install:
    runs-on: macos-latest
    if: github.ref == 'refs/heads/master'

    strategy:
      matrix:
        compiler: [clang, gcc]

    steps:
      - name: Install latest Tig
        run: HOMEBREW_CC=${{ matrix.compiler }} HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_ASK=1 brew install --HEAD tig

  ci:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test Tig
        shell: 'script -q typescript sh {0}' # Workaround to get a TTY, see https://github.com/gfx/example-github-actions-with-tty
        run: |
          HOMEBREW_NO_ASK=1 brew install asciidoc autoconf automake coreutils gnu-sed ncurses xmlto
          TIG_BUILD=autoconf tools/travis.sh
